export const SITE = {
  name: "CoreGenix",
  legalName: "CGCES Pvt Ltd",
  url: "https://coregenix.com",
  description:
    "CoreGenix is an IT infrastructure and cyber security company in Mumbai providing NOC, AMC, Staffing & FMS, cloud, VAPT, managed SOC, GRC and OT security services across India.",
  keywords: [
    "cyber security company",
    "best cyber security company in Mumbai",
    "top cyber security company in India",
    "IT security services",
    "managed security services",
    "VAPT services",
    "NOC AMC Staffing & FMS services",
    "cloud infrastructure management",
    "OT security",
    "GRC & DPO",
  ],
  phone: "+918355958119",
  phoneDisplay: "+91 83559 58119",
  phoneAlt: "+918369339809",
  phoneAltDisplay: "+91 83693 39809",
  email: "sales@cgcein.com",
  emailAlt: "sales@coregenix.in",
  address: {
    street: "C 1405 Kailash Business Park, Park Side, Vikhroli (W)",
    city: "Mumbai",
    state: "Maharashtra",
    postalCode: "400059",
    country: "IN",
    countryName: "India",
  },
  geo: {
    latitude: 19.1083,
    longitude: 72.9253,
  },
  locations: [
    {
      region: "West",
      city: "Mumbai",
      address: "C 1405 Kailash Business Park, Park Side, Vikhroli (W), Mumbai — 400059",
      mapsQuery: "Kailash business park",
      mapsUrl: "https://www.google.com/maps?q=Kailash%20Business%20Park%2C%20Park%20Site%2C%20Vikhroli%20(W)%2C%20Mumbai%20400059&z=15&output=embed",
    },
    {
      region: "South",
      city: "Bengaluru",
      address: "Bengaluru, Karnataka",
      mapsQuery: "bengaluru",
      mapsUrl: "https://maps.google.com/maps?q=bengaluru&t=m&z=7&output=embed",
    },
    {
      region: "North",
      city: "Jaipur",
      address: "Malviya Nagar, Jaipur, Rajasthan",
      mapsQuery: "Malviya nagar jaipur",
      mapsUrl: "https://maps.google.com/maps?q=Malviya%20nagar%20jaipur&t=m&z=10&output=embed",
    },
    {
      region: "Europe",
      city: "Warsaw",
      address: "Warsaw, Poland",
      mapsQuery: "warsaw",
      mapsUrl: "https://maps.google.com/maps?q=warsaw&t=m&z=10&output=embed",
    },
  ],
  hours: [
    { dayOfWeek: "Monday", opens: "09:00", closes: "19:00" },
    { dayOfWeek: "Tuesday", opens: "09:00", closes: "19:00" },
    { dayOfWeek: "Wednesday", opens: "09:00", closes: "19:00" },
    { dayOfWeek: "Thursday", opens: "09:00", closes: "19:00" },
    { dayOfWeek: "Friday", opens: "09:00", closes: "19:00" },
    { dayOfWeek: "Saturday", opens: "09:00", closes: "19:00" },
  ],
  socials: {
    linkedin: "https://in.linkedin.com/company/cgces-pvt-ltd",
    facebook: "https://www.facebook.com/people/CoreGenix/61583901786730/",
  },
  logo: "/images/coregenix/logo.png",
};
